title: Condor GRPC Framework
description: A GRPC Framework for Node
documentation: documentation
google_analytics: UA-92561419-1
documentation: documentation
npm: https://www.npmjs.com/package/condor-framework
links:
  - Documentation: documentation
  - Quick Start: quick-start
  - Adding Services: adding-services
  - GRPC Requests: grpc-requests
  - Middleware: middleware
  - Error Handlers: error-handlers
  - SSL/TLS: ssl-tls
  - Options: options
  - Related Modules and Middleware: related-modules-and-middleware
