title: Condor GRPC Framework
description: A GRPC Framework for Node
menu:
  - Documentation: documentation
links:
  - middleware: middleware
  - error handlers: error-handlers
  - SSL/TLS: ssl-tls
  - Options: options
