theme: jekyll-theme-minimal
title: Condor GRPC Framework
description: A GRPC Framework for Node
links:
  - quick start: quick-start
  - middleware: middleware
  - error handlers: error-handlers
  - SSL/TLS: ssl-tls
  - credits: credits
